export const artistsData = [
  {
    _id: "66CXWjxzNUsdJxJ2JdwvnR",
    name: "Ariana Grande",
    followers: 105394308,
    monthly_listeners: 80991688,
    world_rank: 11,
    genres: ["pop"],
    profile_image: {
      url: "https://i.scdn.co/image/ab6761610000e5eb6725802588d7dc1aba076ca5",
      width: 640,
      height: 640,
    },
    header_image: {
      url: "https://i.scdn.co/image/ab676186000010162f369117de04881a9600b7de",
      width: 2660,
      height: 1140,
    },
    color: "#405860",
    gallery: [
      {
        url: "https://i.scdn.co/image/ab6761670000ecd423c459650d00d16414054cf9",
        width: 640,
        height: 640,
      },
      {
        url: "https://i.scdn.co/image/ab6761670000ecd446580312557152cab8ac4792",
        width: 640,
        height: 640,
      },
    ],
    albums: [
      "6cbwstHlsAIIWurIIXXBPd",
      "7saicsozAZSsKEVQh4WAig",
      "2xqTa2dCR54yYHEcttiXyD",
      "3JUrJP460nFIqwjxM19slT",
      "3L2iweH45rVdTBPldbY6dp",
      "2uMTmPEFafKfKeobvdx5EE",
      "5Csjy4XeA7KnizkhIvI7y2",
      "5EYKrEDnKhhcNxGedaRQeK",
      "2VSBGJ8bUuNgmOYXHIQagM",
      "74vajFwEwXJ61OW1DKSPEa",
      "3euz4vS7ezKGnNSwgyvKcd",
      "5UACk85y1hNRSUtY0ss8pb",
      "2fYhqwDWXjbpjaIJPEfKFw",
      "3tx8gQqWbGwqIGZHqDNrGe",
      "5X7x18kW3mVIvnuNeedM6b",
      "3XBmc6isA4z9BgIO42H2Km",
      "6EVYTRG1drKdO8OnIQBeEj",
      "5xSvNPstcxHtR4ap2vvN8A",
    ],
    top_tracks: [
      "7G0oYXBPOEZUSOAHctUM2U",
      "3lrdiU2zG8mrTGUAAKO7QB",
      "0VfbyDu0kfKEp6FUkteLEJ",
      "4agOc7W9XKQB358QRH0mFq",
      "1I4kQfVvWdKadvAzgcxaT1",
      "1RHbi2GOT3HgCxbJUI9aXR",
      "3qKQJaRUJR8D5wRU0m19sZ",
      "0xfxN2Ro7vFwIn8n8R3TeN",
      "2BiRBX5shWBv0EK3OkoveU",
      "0YGf69JzGkwNUAntkB4Rt0",
      "1nUsYU8wvzfKOoODE91KTa",
      "1SyQd3GJkmIBeQQYZENpId",
      "2Guz7gu1nOe2poG8e20NZZ",
      "1b7hrpeYthxGSbklY3UTvz",
      "1VIkPMOnWl3Xmc1aSpjbWN",
      "2QZB1C9qniDhS6iqxBG8y6",
      "2adOpmJdTo3zAOa0ghiYLi",
      "2aApBbc95H7jB6EmDBGLzW",
      "5Fw8PVO1wNtjB1f3MFOPUY",
      "6ZWn060jvZ5naUOGsQZ0oM",
    ],
    external_links: [
      {
        name: "FACEBOOK",
        url: "https://facebook.com/arianagrande",
      },
      {
        name: "INSTAGRAM",
        url: "https://instagram.com/arianagrande",
      },
    ],
    biography:
      'With her four-octave vocal acrobatics and iconic image, American singer, songwriter, and actress Ariana Grande has solidified her place as one of the quintessential pop stars of her generation, racking up stacks of awards and chart records in the process. Emerging in the early 2010s with the hit single "The Way," Grande was primed to follow in the footsteps of her biggest influences, <a href="spotify:artist:6XpaIBNiVzIetEPCWDvAFP">Whitney Houston</a> and <a href="spotify:artist:4iHNK0tOyZPYnBU7nGAgpQ">Mariah Carey</a>, due in part to her powerhouse vocals. With its <a href="spotify:artist:3aVoqlJOYx31lH1gibGDt3">Babyface</a> production, her debut, Yours Truly, underscored her debt to \'90s R&B, but Grande quickly incorporated hip-hop and EDM into her sound. "Problem," a 2014 smash duet with <a href="spotify:artist:5yG7ZAZafVaAlMTeBybKAL">Iggy Azalea</a>, was the first indication of her development, an evolution reinforced by the hits "Bang Bang" and "Love Me Harder." Grande maintained her popularity with 2016\'s Dangerous Woman, then really hit her stride with 2018\'s Sweetener and its swift sequel, Thank U, Next, whose title track sat atop the U.S. singles chart for seven weeks. That achievement was quickly equaled by the album\'s glitzy second single, "7 Rings," and later with "Positions," the lead single from 2020\'s R&B-heavy album of the same name. After four years without an album -- a relative eternity considering her turn-of-the-decade blitz -- Grande returned with Eternal Sunshine, which she recorded while shooting the film version of Broadway\'s Wicked.\r\n\nA native of Boca Raton, Florida, where she was born in 1993 to graphic designer Edward Butera and Joan Grande (the CEO of Hose-McCann Communications), Grande began singing and acting at an early age, appearing in local theater productions. In 2008, when she was 15, she landed the role of Charlotte in the Broadway production of 13; her performance was well-received, and she won a National Youth Theatre Association Award. Following an appearance in the 2010 <a href="spotify:artist:7KgW65389e5w4xWzaVOuCg">Desmond Child</a>-written musical Cuba Libre, Grande was cast as Cat Valentine in the Nickelodeon television program Victorious. The show ran until 2012, at which time Grande\'s Cat Valentine was spun off into a show called Sam & Cat, which also starred <a href="spotify:artist:3AoFRPmkjP1WTi2Zu7gbZV">Jennette McCurdy</a> of iCarly.\r\n\nAs she kept herself busy with television, Grande began to pursue a musical career. She frequently made appearances at sporting events and with symphonies, and she made her first appearances on record with the soundtrack to Victorious. In 2011, she released the single "Put Your Hearts Up," which was cut during sessions for a teen-oriented pop album; she later disowned the single due to its kiddie feel. Grande felt much more comfortable with "The Way," her 2013 single featuring <a href="spotify:artist:4LLpKhyESsyAXpc4laK94U">Mac Miller</a>. This signaled a mature direction and audiences responded, taking it to the Top Ten in the U.S., where it was eventually certified triple platinum. It was the first single from her 2013 debut, Yours Truly, which also featured hits in "Baby I" and "Right There."\r\n\nAt the end of the year, she released a seasonal EP called Christmas Kisses, but her real efforts went into the recording of her second album, My Everything. Preceded by the single "Problem" -- a song that featured a guest spot from <a href="spotify:artist:5yG7ZAZafVaAlMTeBybKAL">Iggy Azalea</a>, the "It girl" of the summer of 2014; it peaked at two on the U.S. charts and was certified double platinum -- the album featured a host of different producers, including <a href="spotify:artist:1rjeVTt9Ra1ldvN7SpeK0G">Max Martin</a>, Shellback, <a href="spotify:artist:4we5S2VLjgY9KzIzApL1KI">Ryan Tedder</a>, and <a href="spotify:artist:5CiGnKThu5ctn9pBxv7DGa">Benny Blanco</a>. It was released at the end of August 2014, hitting number one on charts across the globe. Subsequent singles featured assists by <a href="spotify:artist:2qxJFvFYMEDqd7ui6kSAcq">Zedd</a> ("Break Free"), <a href="spotify:artist:2gsggkzM5R49q6jpPvazou">Jessie J</a> & <a href="spotify:artist:0hCNtLu0JehylgoiP8L4Gh">Nicki Minaj</a> ("Bang Bang"), and <a href="spotify:artist:1Xyo4u8uXC1ZmMpatF05PJ">the Weeknd</a> ("Love Me Harder"). At one point in 2014, three of her songs were in the Billboard Top Ten at the same time, a feat matched only by <a href="spotify:artist:4dpARuHxo51G3z768sgnrY">Adele</a>. By the time fifth single "One Last Time" charted in early 2015, My Everything had sold nearly 600,000 copies. \r\n\nAs that album\'s cycle wound down, Grande guest-starred on Ryan Murphy\'s campy slasher series Scream Queens and she also recorded another holiday EP, Christmas & Chill. In October 2015, Grande released the single "Focus," which debuted at number seven on the Hot 100 and was certified platinum the following January. That February, she announced her third album, Dangerous Woman, and released the album\'s title track as a single in March. The song hit number eight on the Hot 100, making Grande the first artist to have the lead single from each of her first three albums debut in the Top Ten. Featuring collaborations with <a href="spotify:artist:4ylR3zwA0zaapAu94fktwa">Macy Gray</a>, <a href="spotify:artist:1RyvyyTE3xzB2ZywiAwp0i">Future</a>, and <a href="spotify:artist:0hCNtLu0JehylgoiP8L4Gh">Nicki Minaj</a>, the album appeared in May 2016 and debuted at number two. It eventually went platinum, helped by a trio of Top Ten hits and a Grammy nomination for Best Pop Vocal Album. Grande began 2017 by duetting with <a href="spotify:artist:5y2Xq6xcjJb2jVM54GHK3t">John Legend</a> on "Beauty and the Beast," the title track for <a href="spotify:search:label%3A%22Disney%22">Disney</a>\'s live-action remake of the 1991 animated classic. She then mounted her Dangerous Woman Tour, performing across North America and Europe during the first half of 2017. \r\n\nTragedy struck on May 22, 2017, when a suicide bomber attacked Grande\'s concert at the Manchester Arena in Manchester, England. Grande returned to performing on June 4, when she held a star-studded charity concert called One Love Manchester to aid the victims of the bombing. Following the show, she resumed the Dangerous Woman Tour, which concluded in Hong Kong that September.\r\n\nIn April 2018, Grande kicked off promotion for her fourth album, Sweetener, by issuing the single "No Tears Left to Cry," which debuted at number three on the Hot 100. It was followed by "God Is a Woman" later that year. Upon its release in August 2018, Sweetener debuted at number one in both the U.S. and U.K. \r\n\nThree months after the release of Sweetener, Grande returned with the non-LP single "Thank U, Next." Quickly becoming an internet sensation, "Thank U, Next" shot to number one throughout the world, as did Grande\'s next single, "7 Rings." Both songs were featured on the full-length album Thank U, Next, which appeared in February 2019. Her fourth U.S. number one, the set also topped the charts in over a dozen countries, further buoyed by third single "Break Up with Your Girlfriend, I\'m Bored." Mere months after the release of Thank U, Next, Grande moved on with a series of collaborations, including "Monopoly" with <a href="spotify:artist:63XBtGSEZINSyXylZxEUbv">Victoria Monet</a>, "Boyfriend" with <a href="spotify:artist:5UjifI1TYefXWn9GdqDOHl">Social House</a>, and the Charlie\'s Angels reboot theme "Don\'t Call Me Angel" with <a href="spotify:artist:5YGY8feqx7naU7z4HrwZM6">Miley Cyrus</a> and <a href="spotify:artist:00FQb4jTyendYWaN8pK0wa">Lana Del Rey</a>. Capping off the year, Grande was nominated for five Grammy Awards: Album of the Year and Best Pop Vocal Album for Thank U, Next, Record of the Year and Best Pop Solo Performance for "7 Rings," and Best Pop Duo/Group Performance for "Boyfriend." She capped this prolific period with k bye for now, a live album recorded at various stops throughout her 2019 Sweetener World Tour.\r\n\nGrande had duets reach the top of the Billboard charts in early 2020 -- first it was "Stuck with U" with <a href="spotify:artist:1uNFoZAHBGtllmzznpCI3s">Justin Bieber</a>, then it was "Rain on Me" with <a href="spotify:artist:1HY2Jd0NmPuamShAr6KMms">Lady Gaga</a> -- before she launched her next album, Positions, with the release of its title track. The single reached number one just before the October 30 release of the album, which became her fifth to top the Billboard 200. "34+35" kept her planted toward the upper reaches of the singles chart, boosted by a 2021 remix with <a href="spotify:artist:5cj0lLjcoR7YOSnhnX0Po5">Doja Cat</a> and <a href="spotify:artist:181bsRPaVXVlUKXrxwZfHK">Megan Thee Stallion</a>. That same year, she teamed up with <a href="spotify:artist:1Xyo4u8uXC1ZmMpatF05PJ">the Weeknd</a> on a remix of his song "Save Your Tears," delivering another chart-topper for both artists. They repeated this same success two years later when Grande appeared on a remix of "Die for You" from <a href="spotify:artist:1Xyo4u8uXC1ZmMpatF05PJ">the Weeknd</a>\'s Starboy album.\r\n\nDuring this time, Grande had also pivoted back to acting, appearing in the 2021 ensemble satire Don\'t Look Up, for which she recorded "Just Look Up" with <a href="spotify:artist:0fA0VVWsXO9YnASrzqfmYu">Kid Cudi</a>. She was also cast as Glinda in the film adaptation of Wicked, which began filming in 2022. In 2023, Grande celebrated a decade since her debut with the Yours Truly (Tenth Anniversary Edition) reissue. \r\n\nThe following year, she kicked off her next album cycle with the chart-topping, \'90s-club-inspired "yes, and?" and a remix version featuring <a href="spotify:artist:4iHNK0tOyZPYnBU7nGAgpQ">Mariah Carey</a>. The single paved the way for her seventh overall album, Eternal Sunshine, which arrived in March 2024. A conceptual journey through divorce and the sparks of new love, the set featured production by <a href="spotify:artist:1rjeVTt9Ra1ldvN7SpeK0G">Max Martin</a> and Ilya Salmanzadeh, and balanced upbeat empowerment with reflective vulnerability. The album, which also spawned the Hot 100 singles "We Can\'t Be Friends (Wait for Your Love)" and "The Boy Is Mine," topped the Billboard 200. It also picked up three Grammy nominations, including Best Pop Vocal Album. ~ Stephen Thomas Erlewine, Rovi',
  },
];
